import { useEffect, useMemo, useRef, useState } from 'react';
import Plotly2D from 'plotly.js-basic-dist-min';
import { AttributeEditor, ensureRequiredAttributes, hasRequiredAttributes } from './AttributeEditor';
import { FcbRocketReplayMap, type RocketPosePoint } from './FcbRocketReplayMap';
import { GpsMapView, type GpsEventMarker, type GpsMapPoint } from './GpsMapView';
import type {
  CustomAttribute,
  FlightSummary,
  ImportConfig,
  ImportedDataset,
  DisplayUnitSystem,
  StandardColumnMapping
} from './importTypes';
import {
  getColumnIndexByAliases,
  isValidLatitude,
  isValidLongitude,
  parseNumber
} from './telemetry/core';
import {
  attachPlotHoverDashboard,
  computeEventLabelShifts,
  defaultSeriesIndexes,
  HOVER_DASHBOARD_IDLE_TEXT
} from './plot2dShared';
import {
  buildSingleGpsPlot3dTraces,
  computeGpsPlot3dAspectRatio,
  purgeGpsPlot3d,
  renderGpsPlot3d
} from './plot3dShared';
import {
  parseDisplaySeriesValue,
  seriesDisplayLabel,
  yAxisTitleForSeries
} from './plotUnits';
import { displayUnitLabel, type ColumnUnit } from '../../shared/units';
import {
  buildEventMarkers,
  buildEventWindow,
  buildWindow,
  getImporterId,
  normalizeEventLabel,
  type EventMarker
} from './telemetry/events';
import { buildGpsPoints, findGpsColumns } from './telemetry/gps';
import { computeNorthAlignmentDegrees, normalizeQuaternion } from './telemetry/orientation';
import { buildXAxis, getTimeColumn } from './telemetry/time';

// Altimeter-level: motor moved to the per-flight editor below, so the only
// per-altimeter convenience field is the multiline flight_notes.
const REQUIRED_ATTRIBUTE_KEYS: string[] = [];
const MULTILINE_ATTRIBUTE_KEYS = ['flight_notes'];
const ENSURED_ATTRIBUTE_KEYS = [...REQUIRED_ATTRIBUTE_KEYS, ...MULTILINE_ATTRIBUTE_KEYS];

// Flight-level: shared across all altimeters in the flight, edited once.
const FLIGHT_REQUIRED_ATTRIBUTE_KEYS = ['motor', 'flight_location'];

// Sentinel "altimeter" id for the always-present Flight tab (flight-level attributes).
const FLIGHT_TAB_ID = '__flight__';

// Flight-level keys that are derived/autogenerated and therefore not shown in the
// editor (folder-derived identity + aggregate peak rollups). Everything else in the
// flight file is user-editable (motor, location, and any custom keys).
const FLIGHT_HIDDEN_ATTRIBUTE_KEYS = [
  'flight_date',
  'rocket_name',
  'peak_altitude_m',
  'peak_velocity_ms',
  'peak_acceleration_mss'
];

type FlightViewerProps = {
  config: ImportConfig | null;
  displayUnits: DisplayUnitSystem;
  flight: FlightSummary | null;
  isActive: boolean;
  selectedAltimeterDirectory?: string;
  onDatasetUpdated: () => Promise<FlightSummary[]>;
};

type ViewerSection = 'attributes' | 'plot2d' | 'plot3d' | 'map2d' | 'map3d' | 'rocketReplay' | 'raw';

type FlightEventMarker = EventMarker & {
  canonicalLabel: string;
  sourceImporterId: string;
  sourceLabel: string;
  priority: number;
};

const PAGE_SIZE = 250;
const MAX_EVENT_MARKERS = 200;
const LENGTH_METERS: ColumnUnit = { family: 'length', unit: 'm' };
const EVENT_SOURCE_PRIORITY: Record<string, number> = {
  fcb: 4,
  fcbgroundstation: 4,
  sillygoose: 3,
  easymini: 2,
  stratologgercf: 1
};

function isEventSourceImporter(importerId: string) {
  return importerId in EVENT_SOURCE_PRIORITY;
}

function relativeEventMarkers(dataset: ImportedDataset, autoDetect: boolean): FlightEventMarker[] {
  const rawXAxis = buildXAxis(dataset, { autoDetect });
  const rawEventData = buildEventMarkers(dataset, rawXAxis.values, { autoDetect });
  const launchOffset = buildEventWindow(dataset, rawXAxis.values, { autoDetect }).launchOffset;
  const importerId = getImporterId(dataset);
  const priority = EVENT_SOURCE_PRIORITY[importerId] ?? 0;
  const sourceLabel = dataset.summary.altimeterDirectoryName;

  return rawEventData.events.map((event) => ({
    ...event,
    time: event.time - launchOffset,
    canonicalLabel: normalizeEventLabel(event.label),
    sourceImporterId: importerId,
    sourceLabel,
    priority
  }));
}

function interpolateGpsPoint(points: GpsMapPoint[], targetTime: number): GpsMapPoint | null {
  if (points.length === 0) return null;
  if (targetTime < points[0].time || targetTime > points[points.length - 1].time) {
    return null;
  }

  for (let index = 0; index < points.length; index += 1) {
    const current = points[index];
    if (Math.abs(current.time - targetTime) < 1e-6) {
      return current;
    }

    const next = points[index + 1];
    if (!next) {
      return current;
    }

    if (targetTime > current.time && targetTime < next.time) {
      const span = next.time - current.time;
      if (span <= 0) {
        return current;
      }
      const ratio = (targetTime - current.time) / span;
      return {
        latitude: current.latitude + (next.latitude - current.latitude) * ratio,
        longitude: current.longitude + (next.longitude - current.longitude) * ratio,
        altitude: current.altitude + (next.altitude - current.altitude) * ratio,
        height: current.height + (next.height - current.height) * ratio,
        time: targetTime
      };
    }
  }

  return points[points.length - 1] ?? null;
}

function dedupeFlightEventMarkers(markers: FlightEventMarker[]) {
  const deduped: FlightEventMarker[] = [];

  for (const marker of markers.sort((left, right) => left.time - right.time || right.priority - left.priority)) {
    const existingIndex = deduped.findIndex(
      (candidate) =>
        candidate.canonicalLabel === marker.canonicalLabel && Math.abs(candidate.time - marker.time) <= 1.5
    );

    if (existingIndex < 0) {
      deduped.push(marker);
      continue;
    }

    const existing = deduped[existingIndex];
    if (
      marker.priority > existing.priority ||
      (marker.priority === existing.priority && marker.sourceLabel < existing.sourceLabel)
    ) {
      deduped[existingIndex] = marker;
    }
  }

  return deduped.slice(0, MAX_EVENT_MARKERS);
}

function eventColorForLabel(label: string): [number, number, number, number] {
  if (label === 'DROGUE') return [176, 124, 255, 245];
  if (label === 'MAIN') return [105, 167, 255, 245];
  if (label === 'LANDING') return [255, 110, 110, 245];
  return [255, 191, 102, 240];
}

function buildGpsEventMarkers(
  points: GpsMapPoint[],
  datasets: ImportedDataset[],
  autoDetect: boolean
): GpsEventMarker[] {
  const deduped = dedupeFlightEventMarkers(
    datasets
      .filter((dataset) => isEventSourceImporter(getImporterId(dataset)))
      .flatMap((dataset) => relativeEventMarkers(dataset, autoDetect))
  );

  return deduped
    .map((event, index) => {
      const point = interpolateGpsPoint(points, event.time);
      if (!point) {
        return null;
      }

      return {
        ...point,
        label: event.label,
        sourceLabel: event.sourceLabel,
        color: eventColorForLabel(event.canonicalLabel),
        labelOffsetY: 12 + (index % 3) * 10
      };
    })
    .filter((marker): marker is GpsEventMarker => marker !== null);
}

function findStandardColumns(
  config: ImportConfig | null,
  importerId: string
): StandardColumnMapping | null {
  if (!config || !importerId) return null;
  return (
    config.altimeters.find((altimeter) => altimeter.importerId === importerId)?.standardColumns ?? null
  );
}

export function FlightViewer({
  config,
  displayUnits,
  flight,
  isActive,
  selectedAltimeterDirectory,
  onDatasetUpdated
}: FlightViewerProps) {
  const [selectedDirectory, setSelectedDirectory] = useState('');
  const [dataset, setDataset] = useState<ImportedDataset | null>(null);
  const [loadError, setLoadError] = useState('');
  const [activeSection, setActiveSection] = useState<ViewerSection>('attributes');
  const [attributes, setAttributes] = useState<CustomAttribute[]>([]);
  const [selectedSeries, setSelectedSeries] = useState<number[]>([]);
  const [hoverText, setHoverText] = useState(HOVER_DASHBOARD_IDLE_TEXT);
  const [showFullData, setShowFullData] = useState(false);
  const [sanitizeData, setSanitizeData] = useState(true);
  const [autoDetect, setAutoDetect] = useState(true);
  const [showEvents, setShowEvents] = useState(true);
  const [rawPage, setRawPage] = useState(0);
  const [saveStatus, setSaveStatus] = useState('');
  const [saveError, setSaveError] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [eventDatasets, setEventDatasets] = useState<ImportedDataset[]>([]);
  const [flightAttributes, setFlightAttributes] = useState<CustomAttribute[]>([]);
  const [loadedFlightAttributes, setLoadedFlightAttributes] = useState<CustomAttribute[]>([]);
  const [flightSaveStatus, setFlightSaveStatus] = useState('');
  const [flightSaveError, setFlightSaveError] = useState('');
  const [isSavingFlight, setIsSavingFlight] = useState(false);
  const plot2dRef = useRef<HTMLDivElement | null>(null);
  const plot3dRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!flight) {
      setSelectedDirectory('');
      return;
    }

    setSelectedDirectory((current) => {
      const requested = selectedAltimeterDirectory;
      if (requested && flight.altimeters.some((altimeter) => altimeter.altimeterDirectory === requested)) {
        return requested;
      }

      if (current === FLIGHT_TAB_ID) {
        return current;
      }

      if (current && flight.altimeters.some((altimeter) => altimeter.altimeterDirectory === current)) {
        return current;
      }

      return flight.altimeters[0]?.altimeterDirectory ?? '';
    });
  }, [flight, selectedAltimeterDirectory]);

  useEffect(() => {
    const flightDirectoryName = flight?.directoryName;
    if (!flightDirectoryName) {
      setFlightAttributes([]);
      setLoadedFlightAttributes([]);
      return;
    }

    let ignore = false;
    setFlightSaveStatus('');
    setFlightSaveError('');

    window.appBridge
      .readFlightAttributes(flightDirectoryName)
      .then((attrs) => {
        if (ignore) return;
        // Show all editable keys (motor, location, and any custom ones the user
        // added); hide derived/autogenerated keys, which are preserved server-side.
        const editable = ensureRequiredAttributes(
          attrs.filter((attribute) => !FLIGHT_HIDDEN_ATTRIBUTE_KEYS.includes(attribute.key)),
          FLIGHT_REQUIRED_ATTRIBUTE_KEYS
        );
        setFlightAttributes(editable);
        setLoadedFlightAttributes(editable);
      })
      .catch(() => {
        if (ignore) return;
        const editable = ensureRequiredAttributes([], FLIGHT_REQUIRED_ATTRIBUTE_KEYS);
        setFlightAttributes(editable);
        setLoadedFlightAttributes(editable);
      });

    return () => {
      ignore = true;
    };
  }, [flight?.directoryName]);

  useEffect(() => {
    if (!selectedDirectory || selectedDirectory === FLIGHT_TAB_ID) {
      setDataset(null);
      return;
    }

    let ignore = false;
    setLoadError('');
    const started = performance.now();
    void window.appBridge.debugLog('viewer:read-dataset:start', {
      selectedDirectory,
      sanitize: sanitizeData
    });

    window.appBridge
      .readDataset(selectedDirectory, { sanitize: sanitizeData })
      .then((nextDataset) => {
        if (ignore) return;
        setDataset(nextDataset);
        setAttributes(ensureRequiredAttributes(nextDataset.attributes, ENSURED_ATTRIBUTE_KEYS));
        const importerId =
          nextDataset.attributes.find((attr) => attr.key === 'importer_id')?.value ?? '';
        setSelectedSeries(
          defaultSeriesIndexes(
            nextDataset.headers,
            getTimeColumn(nextDataset.headers, nextDataset.rows, { autoDetect })?.index ?? null,
            findStandardColumns(config, importerId)
          )
        );
        setShowFullData(false);
        setRawPage(0);
        void window.appBridge.debugLog('viewer:read-dataset:ok', {
          selectedDirectory,
          durationMs: Math.round(performance.now() - started),
          rowCount: nextDataset.rows.length,
          headerCount: nextDataset.headers.length,
          sanitize: sanitizeData
        });
      })
      .catch((error: Error) => {
        if (!ignore) {
          setLoadError(error.message);
          void window.appBridge.debugLog('viewer:read-dataset:error', {
            selectedDirectory,
            durationMs: Math.round(performance.now() - started),
            message: error.message
          });
        }
      });

    return () => {
      ignore = true;
    };
  }, [sanitizeData, config, selectedDirectory]);

  const hasAttributeChanges = useMemo(() => {
    if (!dataset) return false;
    const ensured = ensureRequiredAttributes(dataset.attributes, ENSURED_ATTRIBUTE_KEYS);
    return JSON.stringify(attributes) !== JSON.stringify(ensured);
  }, [attributes, dataset]);

  const hasRequiredFilled = hasRequiredAttributes(attributes, REQUIRED_ATTRIBUTE_KEYS);

  const rawXAxis = useMemo(
    () => (dataset ? buildXAxis(dataset, { autoDetect }) : { values: [], title: 'Row', hoverLabel: 'row' }),
    [autoDetect, dataset]
  );

  const rawEventData = useMemo(() => {
    if (!dataset) {
      return {
        events: [] as EventMarker[],
        launchTime: null as number | null,
        flightStartTime: 0,
        flightEndTime: 0
      };
    }
    return buildEventMarkers(dataset, rawXAxis.values, { autoDetect });
  }, [autoDetect, dataset, rawXAxis.values]);
  const gpsColumns = useMemo(() => {
    if (!dataset) {
      return null;
    }

    const gpsPositionColumns = findGpsColumns(dataset.headers, dataset.rows, { autoDetect });
    const altitudeIndex = getColumnIndexByAliases(dataset.headers, [
      'altitude',
      'altitude_m',
      'altitudem',
      'gps_alt'
    ]);

    if (!gpsPositionColumns || altitudeIndex === null) {
      return null;
    }

    return { ...gpsPositionColumns, altitudeIndex };
  }, [autoDetect, dataset]);
  const launchOffset = useMemo(
    () => (dataset ? buildEventWindow(dataset, rawXAxis.values, { autoDetect }).launchOffset : 0),
    [autoDetect, dataset, rawXAxis.values]
  );

  const xAxis = useMemo(
    () =>
      launchOffset === 0
        ? rawXAxis
        : { ...rawXAxis, values: rawXAxis.values.map((value) => value - launchOffset) },
    [rawXAxis, launchOffset]
  );
  const xValues = xAxis.values;

  const eventData = useMemo(
    () => {
      if (launchOffset === 0) {
        return rawEventData;
      }

      const relativeEndTime = (rawXAxis.values[rawXAxis.values.length - 1] ?? launchOffset) - launchOffset;
      const hasEventLaunch = rawEventData.launchTime !== null;

      return {
        ...rawEventData,
        events: rawEventData.events.map((event) => ({ ...event, time: event.time - launchOffset })),
        flightStartTime: hasEventLaunch ? rawEventData.flightStartTime - launchOffset : 0,
        flightEndTime: hasEventLaunch ? rawEventData.flightEndTime - launchOffset : relativeEndTime
      };
    },
    [rawEventData, launchOffset, rawXAxis.values]
  );

  const dataWindow = useMemo(
    () => buildWindow(xValues, eventData.flightStartTime, eventData.flightEndTime),
    [eventData.flightEndTime, eventData.flightStartTime, xValues]
  );

  const visibleIndexes = useMemo(() => {
    if (showFullData) {
      return dataset?.rows.map((_, index) => index) ?? [];
    }

    return xValues
      .map((time, index) => ({ time, index }))
      .filter(({ time }) => time >= dataWindow.start && time <= dataWindow.end)
      .map(({ index }) => index);
  }, [dataWindow.end, dataWindow.start, dataset, showFullData, xValues]);

  const visibleRows = useMemo(
    () => visibleIndexes.map((index) => dataset?.rows[index] ?? []),
    [dataset, visibleIndexes]
  );
  const visibleXValues = useMemo(() => visibleIndexes.map((index) => xValues[index]), [visibleIndexes, xValues]);
  const visibleEvents = useMemo(
    () =>
      eventData.events.filter((event) =>
        showFullData ? true : event.time >= dataWindow.start && event.time <= dataWindow.end
      ),
    [dataWindow.end, dataWindow.start, eventData.events, showFullData]
  );
  const plotEvents = useMemo(
    () => (showEvents ? visibleEvents : []),
    [showEvents, visibleEvents]
  );

  const eventLabelShifts = useMemo(
    () => computeEventLabelShifts(plotEvents, visibleXValues),
    [plotEvents, visibleXValues]
  );
  const gpsPoints = useMemo(() => {
    if (!gpsColumns) {
      return [];
    }

    const launchAltitude =
      visibleRows
        .map((row) => parseNumber(row[gpsColumns.altitudeIndex]))
        .find((value) => value !== null) ?? 0;

    return buildGpsPoints(visibleRows, visibleXValues, gpsColumns, launchAltitude);
  }, [gpsColumns, visibleRows, visibleXValues]);
  const gpsAspectRatio = useMemo(() => computeGpsPlot3dAspectRatio(gpsPoints), [gpsPoints]);
  const selectedImporterId = dataset ? getImporterId(dataset) : '';
  const fcbRocketSamples = useMemo((): RocketPosePoint[] => {
    if (!dataset || selectedImporterId !== 'fcb' || !gpsColumns) {
      return [];
    }

    const qxIndex = getColumnIndexByAliases(dataset.headers, ['q_x', 'quaternion_x']);
    const qyIndex = getColumnIndexByAliases(dataset.headers, ['q_y', 'quaternion_y']);
    const qzIndex = getColumnIndexByAliases(dataset.headers, ['q_z', 'quaternion_z']);
    const qwIndex = getColumnIndexByAliases(dataset.headers, ['q_w', 'quaternion_w']);

    if (qxIndex === null || qyIndex === null || qzIndex === null || qwIndex === null) {
      return [];
    }

    const quaternionColumns = { qxIndex, qyIndex, qzIndex, qwIndex };
    const northCorrectionDeg = computeNorthAlignmentDegrees(dataset, xValues, gpsColumns, quaternionColumns);

    const launchAltitude =
      visibleRows
        .map((row) => parseNumber(row[gpsColumns.altitudeIndex]))
        .find((value) => value !== null) ?? 0;

    return visibleRows
      .map((row, index) => {
        const latitude = parseNumber(row[gpsColumns.latitudeIndex]);
        const longitude = parseNumber(row[gpsColumns.longitudeIndex]);
        const altitude = parseNumber(row[gpsColumns.altitudeIndex]);
        const qx = parseNumber(row[qxIndex]);
        const qy = parseNumber(row[qyIndex]);
        const qz = parseNumber(row[qzIndex]);
        const qw = parseNumber(row[qwIndex]);
        const time = visibleXValues[index];

        if (
          latitude === null ||
          longitude === null ||
          altitude === null ||
          !isValidLatitude(latitude) ||
          !isValidLongitude(longitude) ||
          qx === null ||
          qy === null ||
          qz === null ||
          qw === null ||
          !Number.isFinite(time)
        ) {
          return null;
        }

        const quaternion = normalizeQuaternion(qx, qy, qz, qw);
        if (!quaternion) {
          return null;
        }

        return {
          latitude,
          longitude,
          altitude,
          height: Math.max(0, altitude - launchAltitude),
          time,
          northCorrectionDeg,
          ...quaternion
        };
      })
      .filter((sample): sample is RocketPosePoint => sample !== null);
  }, [dataset, gpsColumns, selectedImporterId, visibleRows, visibleXValues, xValues]);
  const gpsViewActive =
    activeSection === 'plot3d' ||
    activeSection === 'map2d' ||
    activeSection === 'map3d' ||
    activeSection === 'rocketReplay';

  useEffect(() => {
    if (!flight || !dataset || !gpsColumns || !gpsViewActive) {
      setEventDatasets([]);
      return;
    }

    let ignore = false;
    const relevantAltimeters = flight.altimeters.filter((altimeter) =>
      isEventSourceImporter(altimeter.attributes.importer_id ?? '')
    );

    Promise.all(
      relevantAltimeters.map((altimeter) => {
        if (altimeter.altimeterDirectory === selectedDirectory) {
          return Promise.resolve(dataset);
        }

        return window.appBridge
          .readDataset(altimeter.altimeterDirectory, { sanitize: sanitizeData })
          .catch(() => null);
      })
    ).then((datasets) => {
      if (ignore) return;
      setEventDatasets(datasets.filter((entry): entry is ImportedDataset => entry !== null));
    });

    return () => {
      ignore = true;
    };
  }, [sanitizeData, dataset, flight, gpsColumns, gpsViewActive, selectedDirectory]);

  const gpsEventMarkers = useMemo(
    () => buildGpsEventMarkers(gpsPoints, eventDatasets, autoDetect),
    [autoDetect, eventDatasets, gpsPoints]
  );

  useEffect(() => {
    setRawPage(0);
  }, [dataset, showFullData]);

  useEffect(() => {
    const plotElement = plot2dRef.current;
    if (!isActive || !plotElement || !dataset || activeSection !== 'plot2d') {
      return;
    }
    const started = performance.now();
    void window.appBridge.debugLog('viewer:plot2d:start', {
      selectedDirectory,
      selectedSeriesCount: selectedSeries.length,
      visiblePointCount: visibleRows.length,
      visibleEventCount: plotEvents.length
    });

    const traces = selectedSeries.map((seriesIndex) => ({
      x: visibleXValues,
      y: visibleRows.map((row) =>
        parseDisplaySeriesValue(
          row[seriesIndex],
          dataset.headers[seriesIndex],
          dataset.columnUnits,
          displayUnits
        )
      ),
      name: seriesDisplayLabel(
        dataset.headers[seriesIndex],
        dataset.headers[seriesIndex],
        dataset.columnUnits,
        displayUnits
      ),
      mode: 'lines',
      type: 'scatter',
      hoverinfo: 'none'
    }));
    const yAxisTitle = yAxisTitleForSeries(
      selectedSeries.map((seriesIndex) => dataset.headers[seriesIndex]),
      dataset.columnUnits,
      displayUnits
    );

    Plotly2D.newPlot(
      plotElement,
      traces,
      {
        autosize: true,
        paper_bgcolor: 'rgba(0,0,0,0)',
        plot_bgcolor: 'rgba(0,0,0,0)',
        font: { color: '#e4e7eb' },
        margin: { t: 24, r: 24, b: 48, l: 64 },
        hovermode: 'x',
        shapes: plotEvents.map((event) => ({
          type: 'line',
          x0: event.time,
          x1: event.time,
          y0: 0,
          y1: 1,
          yref: 'paper',
          line: { color: event.color, width: 1, dash: 'dash' }
        })),
        annotations: plotEvents.map((event, index) => ({
          x: event.time,
          y: 1,
          yref: 'paper',
          yanchor: 'top',
          yshift: eventLabelShifts[index] ?? 0,
          text: event.label,
          showarrow: false,
          textangle: -90,
          xanchor: 'right',
          font: { color: event.color, size: 10 }
        })),
        xaxis: {
          title: { text: xAxis.title, standoff: 12 },
          automargin: true,
          gridcolor: '#30343a',
          showspikes: true,
          spikemode: 'across',
          spikesnap: 'cursor',
          spikedash: 'dash',
          spikecolor: '#aab2bd',
          spikethickness: 1
        },
        yaxis: {
          title: yAxisTitle,
          gridcolor: '#30343a'
        },
        legend: {
          orientation: 'h',
          yanchor: 'bottom',
          y: 1.02,
          xanchor: 'right',
          x: 1
        }
      },
      {
        responsive: true,
        displaylogo: false,
        scrollZoom: true
      }
    ).then(() => {
      void window.appBridge.debugLog('viewer:plot2d:ok', {
        selectedDirectory,
        durationMs: Math.round(performance.now() - started),
        selectedSeriesCount: selectedSeries.length,
        visiblePointCount: visibleRows.length,
        visibleEventCount: plotEvents.length
      });
      attachPlotHoverDashboard(plotElement, xAxis, setHoverText);
      Plotly2D.Plots.resize(plotElement);
    });

    return () => {
      Plotly2D.purge(plotElement);
    };
  }, [
    activeSection,
    dataset,
    eventLabelShifts,
    isActive,
    selectedSeries,
    displayUnits,
    plotEvents,
    visibleRows,
    visibleXValues,
    xAxis.hoverLabel,
    xAxis.title
  ]);

  useEffect(() => {
    const plotElement = plot3dRef.current;
    if (!isActive || !plotElement || !dataset || activeSection !== 'plot3d' || !gpsColumns) {
      return;
    }

    void renderGpsPlot3d(
      plotElement,
      buildSingleGpsPlot3dTraces(gpsPoints, gpsEventMarkers, displayUnits),
      gpsAspectRatio,
      `Altitude (${displayUnitLabel(LENGTH_METERS, displayUnits)})`
    );

    return () => {
      purgeGpsPlot3d(plotElement);
    };
  }, [activeSection, dataset, displayUnits, gpsAspectRatio, gpsColumns, gpsEventMarkers, gpsPoints, isActive]);

  const saveAttributes = async () => {
    if (!dataset || !hasAttributeChanges) return;

    setIsSaving(true);
    setSaveStatus('');
    setSaveError('');

    try {
      const nextDataset = await window.appBridge.saveDatasetAttributes({
        datasetDirectory: selectedDirectory,
        attributes
      });
      setDataset(nextDataset);
      setAttributes(nextDataset.attributes);
      setSaveStatus('Attributes saved.');
      await onDatasetUpdated();
    } catch (error) {
      setSaveError(error instanceof Error ? error.message : 'Unable to save attributes.');
    } finally {
      setIsSaving(false);
    }
  };

  const hasFlightChanges = useMemo(
    () => JSON.stringify(flightAttributes) !== JSON.stringify(loadedFlightAttributes),
    [flightAttributes, loadedFlightAttributes]
  );
  const hasFlightRequiredFilled = hasRequiredAttributes(flightAttributes, FLIGHT_REQUIRED_ATTRIBUTE_KEYS);

  const saveFlightAttributes = async () => {
    if (!flight || !hasFlightChanges) return;

    setIsSavingFlight(true);
    setFlightSaveStatus('');
    setFlightSaveError('');

    try {
      await window.appBridge.saveFlightAttributes({
        flightDirectoryName: flight.directoryName,
        attributes: flightAttributes
      });
      setLoadedFlightAttributes(flightAttributes);
      setFlightSaveStatus('Flight attributes saved.');
      await onDatasetUpdated();
    } catch (error) {
      setFlightSaveError(error instanceof Error ? error.message : 'Unable to save flight attributes.');
    } finally {
      setIsSavingFlight(false);
    }
  };

  if (!flight) {
    return <div className="muted-text">Flight is not available in the current directory.</div>;
  }

  if (loadError) {
    return <div className="error-text">{loadError}</div>;
  }

  const isFlightTab = selectedDirectory === FLIGHT_TAB_ID;
  const numericSeries =
    dataset?.headers.map((header, index) => ({ header, index })).filter((series) => series.index > 0) ?? [];
  const totalPages = Math.max(1, Math.ceil(visibleRows.length / PAGE_SIZE));
  const boundedPage = Math.min(rawPage, totalPages - 1);
  const pagedRows = visibleRows.slice(boundedPage * PAGE_SIZE, (boundedPage + 1) * PAGE_SIZE);

  return (
    <div className="viewer">
      <header className="viewer-header">
        <div>
          <h2>{flight.directoryName}</h2>
        </div>
        <button
          className="small-button"
          onClick={() => setShowFullData((current) => !current)}
          type="button"
        >
          {showFullData ? 'Flight Window' : 'Full Data'}
        </button>
        <label className="checkbox-row toolbar-checkbox">
          <input
            checked={sanitizeData}
            onChange={(event) => setSanitizeData(event.target.checked)}
            type="checkbox"
          />
          <span title="Blank out-of-range / corrupt values while parsing">Sanitize data</span>
        </label>
        <label className="checkbox-row toolbar-checkbox">
          <input
            checked={autoDetect}
            onChange={(event) => setAutoDetect(event.target.checked)}
            type="checkbox"
          />
          <span title="Auto-detect time units, GPS columns, and flight events">Auto-detect</span>
        </label>
        <label className="checkbox-row toolbar-checkbox">
          <input
            checked={showEvents}
            onChange={(event) => setShowEvents(event.target.checked)}
            type="checkbox"
          />
          <span title="Show flight event markers on the 2D plot">Show events</span>
        </label>
      </header>

      <nav className="altimeter-tabbar" aria-label="Altimeters">
        <button
          className={selectedDirectory === FLIGHT_TAB_ID ? 'active' : ''}
          onClick={() => setSelectedDirectory(FLIGHT_TAB_ID)}
          type="button"
        >
          Flight
        </button>
        {flight.altimeters.map((altimeter) => (
          <button
            className={selectedDirectory === altimeter.altimeterDirectory ? 'active' : ''}
            key={altimeter.id}
            onClick={() => setSelectedDirectory(altimeter.altimeterDirectory)}
            type="button"
          >
            {altimeter.altimeterDirectoryName}
          </button>
        ))}
      </nav>

      <div className={`viewer-body${isFlightTab ? ' viewer-body--single' : ''}`}>
        {isFlightTab ? (
          <div className="viewer-content">
            <section className="viewer-panel">
              <div className="panel-header">
                <h2>Flight Attributes</h2>
                <span>Shared by all altimeters · {flight.directoryName}</span>
              </div>
              <AttributeEditor
                attributes={flightAttributes}
                emptyText="No flight attributes."
                onChange={setFlightAttributes}
                requiredKeys={FLIGHT_REQUIRED_ATTRIBUTE_KEYS}
              />
              <footer className="import-actions">
                {flightSaveStatus ? <div className="success-text">{flightSaveStatus}</div> : null}
                {flightSaveError ? <div className="error-text">{flightSaveError}</div> : null}
                {!hasFlightRequiredFilled ? (
                  <div className="warning-text">Motor and flight location are required.</div>
                ) : null}
                <button
                  className="primary-button"
                  disabled={!hasFlightChanges || !hasFlightRequiredFilled || isSavingFlight}
                  onClick={saveFlightAttributes}
                  type="button"
                >
                  {isSavingFlight ? 'Saving' : 'Save Flight Attributes'}
                </button>
              </footer>
            </section>
          </div>
        ) : (
        <>
        <nav className="view-sidebar" aria-label="Dataset views">
          <button
            className={activeSection === 'attributes' ? 'active' : ''}
            onClick={() => setActiveSection('attributes')}
            type="button"
          >
            Attributes
          </button>
          <button
            className={activeSection === 'plot2d' ? 'active' : ''}
            onClick={() => setActiveSection('plot2d')}
            type="button"
          >
            2D Plot
          </button>
          <button
            className={activeSection === 'plot3d' ? 'active' : ''}
            onClick={() => setActiveSection('plot3d')}
            type="button"
          >
            3D Graph
          </button>
          <button
            className={activeSection === 'map2d' ? 'active' : ''}
            onClick={() => setActiveSection('map2d')}
            type="button"
          >
            Flight Map
          </button>
          <button
            className={activeSection === 'map3d' ? 'active' : ''}
            onClick={() => setActiveSection('map3d')}
            type="button"
          >
            Flight Map 3D
          </button>
          <button
            className={activeSection === 'rocketReplay' ? 'active' : ''}
            onClick={() => setActiveSection('rocketReplay')}
            type="button"
          >
            Rocket Replay
          </button>
          <button
            className={activeSection === 'raw' ? 'active' : ''}
            onClick={() => setActiveSection('raw')}
            type="button"
          >
            Raw Data
          </button>
        </nav>

        <div className="viewer-content">
          {!dataset ? <div className="muted-text">Loading dataset...</div> : null}

          {dataset && activeSection === 'attributes' ? (
            <section className="viewer-panel">
              <div className="panel-header">
                <h2>Altimeter Attributes</h2>
                <span>{dataset.summary.altimeterDirectoryName}</span>
              </div>
              <AttributeEditor
                attributes={attributes}
                emptyText="No attributes."
                onChange={(next) => setAttributes(ensureRequiredAttributes(next, ENSURED_ATTRIBUTE_KEYS))}
                requiredKeys={REQUIRED_ATTRIBUTE_KEYS}
                multilineKeys={MULTILINE_ATTRIBUTE_KEYS}
              />
              <footer className="import-actions">
                {saveStatus ? <div className="success-text">{saveStatus}</div> : null}
                {saveError ? <div className="error-text">{saveError}</div> : null}
                <button
                  className="primary-button"
                  disabled={!hasAttributeChanges || !hasRequiredFilled || isSaving}
                  onClick={saveAttributes}
                  type="button"
                >
                  {isSaving ? 'Saving' : 'Save Attributes'}
                </button>
              </footer>
            </section>
          ) : null}

          {dataset && activeSection === 'plot2d' ? (
            <section className="plot-layout">
              <aside className="series-panel">
                <div className="section-title">Series</div>
                <div className="series-list">
                  {numericSeries.map((series) => (
                    <label className="checkbox-row" key={series.index}>
                      <input
                        checked={selectedSeries.includes(series.index)}
                        onChange={(event) => {
                          setSelectedSeries((current) =>
                            event.target.checked
                              ? [...current, series.index]
                              : current.filter((index) => index !== series.index)
                          );
                        }}
                        type="checkbox"
                      />
                      {dataset
                        ? seriesDisplayLabel(series.header, series.header, dataset.columnUnits, displayUnits)
                        : series.header}
                    </label>
                  ))}
                </div>
              </aside>
              <div className="plot-main">
                <div className="hover-dashboard">{hoverText}</div>
                <div className="plot-surface" ref={plot2dRef} />
              </div>
            </section>
          ) : null}

          {dataset && activeSection === 'plot3d' ? (
            <section className="plot3d-layout">
              {gpsColumns ? (
                <div className="plot-surface" ref={plot3dRef} />
              ) : (
                <div className="viewer-panel">
                  <h2>3D Plot</h2>
                  <p>No GPS 3D dataset is available for this altimeter.</p>
                </div>
              )}
            </section>
          ) : null}

          {dataset && activeSection === 'map2d' ? (
            <section className="plot3d-layout">
              {gpsColumns ? (
                <GpsMapView
                  eventMarkers={gpsEventMarkers}
                  isActive={isActive}
                  mode="map2d"
                  points={gpsPoints}
                />
              ) : (
                <div className="viewer-panel">
                  <h2>Flight Map</h2>
                  <p>No GPS dataset is available for this altimeter.</p>
                </div>
              )}
            </section>
          ) : null}

          {dataset && activeSection === 'map3d' ? (
            <section className="plot3d-layout">
              {gpsColumns ? (
                <GpsMapView
                  eventMarkers={gpsEventMarkers}
                  isActive={isActive}
                  mode="map3d"
                  points={gpsPoints}
                />
              ) : (
                <div className="viewer-panel">
                  <h2>Flight Map 3D</h2>
                  <p>No GPS dataset is available for this altimeter.</p>
                </div>
              )}
            </section>
          ) : null}

          {dataset && activeSection === 'rocketReplay' ? (
            <section className="plot3d-layout">
              {selectedImporterId === 'fcb' ? (
                <FcbRocketReplayMap
                  eventMarkers={gpsEventMarkers}
                  isActive={isActive}
                  samples={fcbRocketSamples}
                />
              ) : (
                <div className="viewer-panel">
                  <h2>Rocket Replay</h2>
                  <p>Rocket replay is currently only supported for FCB altimeters.</p>
                </div>
              )}
            </section>
          ) : null}

          {dataset && activeSection === 'raw' ? (
            <section className="raw-data-shell">
              <div className="raw-toolbar">
                <span>
                  Rows {visibleRows.length === 0 ? 0 : boundedPage * PAGE_SIZE + 1}-
                  {Math.min((boundedPage + 1) * PAGE_SIZE, visibleRows.length)} of {visibleRows.length}
                </span>
                <div className="pager">
                  <button
                    className="small-button"
                    disabled={boundedPage === 0}
                    onClick={() => setRawPage((page) => Math.max(0, page - 1))}
                    type="button"
                  >
                    Previous
                  </button>
                  <span>
                    {boundedPage + 1} / {totalPages}
                  </span>
                  <button
                    className="small-button"
                    disabled={boundedPage >= totalPages - 1}
                    onClick={() => setRawPage((page) => Math.min(totalPages - 1, page + 1))}
                    type="button"
                  >
                    Next
                  </button>
                </div>
              </div>
              <div className="raw-data-panel">
                <table className="data-table">
                  <thead>
                    <tr>
                      {dataset.headers.map((header) => (
                        <th key={header}>{header}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {pagedRows.map((row, rowIndex) => (
                      <tr key={`${boundedPage}-${rowIndex}`}>
                        {dataset.headers.map((header, columnIndex) => (
                          <td key={`${rowIndex}-${header}`}>{row[columnIndex]}</td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </section>
          ) : null}
        </div>
        </>
        )}
      </div>
    </div>
  );
}
