/*
 * One-time migration: hoist shared flight-level attributes into a per-flight
 * attributes.csv and remove the duplicated keys from each altimeter file.
 *
 *   flight-level (authoritative): flight_date, rocket_name, flight_location, motor
 *   flight-level (autogenerated rollup): peak_altitude_m/velocity_ms/acceleration_mss = max across altimeters
 *
 * Idempotent: re-running merges into the existing flight file. Self-verifies
 * that each altimeter's effective flight-level values are unchanged.
 *
 *   node <bundled>.cjs            # migrate
 *   node <bundled>.cjs --check    # report only, write nothing
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const FLIGHT_DATA_DIR = path.resolve('flight-data');
const ATTRIBUTES_FILE_NAME = 'attributes.csv';
const FLIGHT_KEYS = ['flight_date', 'rocket_name', 'flight_location', 'motor'] as const;
const PEAK_KEYS = [
  ['peak_altitude_m', 2],
  ['peak_velocity_ms', 2],
  ['peak_acceleration_mss', 2]
] as const;

type Attr = { key: string; value: string };

function csvCell(value: string) {
  return /[",\r\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value;
}

function parseCsvLine(line: string): string[] {
  const values: string[] = [];
  let current = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i += 1) {
    const ch = line[i];
    if (ch === '"') {
      if (inQuotes && line[i + 1] === '"') {
        current += '"';
        i += 1;
      } else {
        inQuotes = !inQuotes;
      }
    } else if (ch === ',' && !inQuotes) {
      values.push(current);
      current = '';
    } else {
      current += ch;
    }
  }
  values.push(current);
  return values;
}

async function readAttrs(filePath: string): Promise<Attr[] | null> {
  let contents: string;
  try {
    contents = await readFile(filePath, 'utf8');
  } catch {
    return null;
  }
  const rows = contents.split(/\r?\n/).filter((line) => line.length > 0).map(parseCsvLine);
  const dataRows = rows[0]?.[0] === 'key' && rows[0]?.[1] === 'value' ? rows.slice(1) : rows;
  return dataRows.filter((row) => row[0]).map((row) => ({ key: row[0] ?? '', value: row[1] ?? '' }));
}

async function writeAttrs(filePath: string, attrs: Attr[]) {
  const body = [
    csvCell('key') + ',' + csvCell('value'),
    ...attrs.filter((a) => a.key.trim()).map((a) => `${csvCell(a.key.trim())},${csvCell(a.value)}`)
  ].join('\n');
  await writeFile(filePath, `${body}\n`, 'utf8');
}

function toRecord(attrs: Attr[]): Record<string, string> {
  return attrs.reduce<Record<string, string>>((acc, a) => {
    acc[a.key] = a.value;
    return acc;
  }, {});
}

function firstNonEmpty(values: (string | undefined)[]): string | undefined {
  return values.find((value) => value !== undefined && value !== '');
}

// A value carries real information (not blank, not the "unknown" placeholder).
function isMeaningful(value: string | undefined): value is string {
  return value !== undefined && value !== '' && value.toLowerCase() !== 'unknown';
}

async function main() {
  const checkOnly = process.argv.includes('--check');
  const flightEntries = await readdir(FLIGHT_DATA_DIR, { withFileTypes: true });
  let migratedFlights = 0;
  let rewrittenAltimeters = 0;
  const warnings: string[] = [];
  const verifyFailures: string[] = [];

  for (const flightEntry of flightEntries) {
    if (!flightEntry.isDirectory()) continue;
    const flightDir = path.join(FLIGHT_DATA_DIR, flightEntry.name);
    const altimeterEntries = await readdir(flightDir, { withFileTypes: true });

    const altimeters: { name: string; file: string; attrs: Attr[]; record: Record<string, string> }[] = [];
    for (const altimeterEntry of altimeterEntries) {
      if (!altimeterEntry.isDirectory()) continue;
      const file = path.join(flightDir, altimeterEntry.name, ATTRIBUTES_FILE_NAME);
      const attrs = await readAttrs(file);
      if (attrs) altimeters.push({ name: altimeterEntry.name, file, attrs, record: toRecord(attrs) });
    }
    if (altimeters.length === 0) continue;

    // Capture the effective flight-level values each altimeter has TODAY.
    const expected = new Map<string, Record<string, string>>();
    const existingFlight = toRecord((await readAttrs(path.join(flightDir, ATTRIBUTES_FILE_NAME))) ?? []);
    for (const altimeter of altimeters) {
      const eff: Record<string, string> = {};
      for (const key of FLIGHT_KEYS) {
        eff[key] = existingFlight[key] || altimeter.record[key] || '';
      }
      expected.set(altimeter.name, eff);
    }

    // Build the flight record: prefer an existing flight value, then the first
    // meaningful altimeter value, then any non-empty value (e.g. "unknown").
    const flightRecord: Record<string, string> = { ...existingFlight };
    for (const key of FLIGHT_KEYS) {
      const candidates = [existingFlight[key], ...altimeters.map((a) => a.record[key])];
      const resolved = candidates.find(isMeaningful) ?? firstNonEmpty(candidates) ?? '';
      if (resolved !== '') flightRecord[key] = resolved;

      const distinctMeaningful = new Set(altimeters.map((a) => a.record[key]).filter(isMeaningful));
      if (distinctMeaningful.size > 1) {
        warnings.push(`${flightEntry.name}: altimeters disagree on "${key}" (${[...distinctMeaningful].join(' | ')}); kept "${flightRecord[key]}"`);
      }
    }
    for (const [peakKey, digits] of PEAK_KEYS) {
      const values = altimeters
        .map((a) => Number.parseFloat(a.record[peakKey] ?? ''))
        .filter((value) => Number.isFinite(value));
      if (values.length > 0) flightRecord[peakKey] = Math.max(...values).toFixed(digits);
    }

    // Order flight file: flight keys, peak keys, then anything else already present.
    const orderedKeys = [
      ...FLIGHT_KEYS,
      ...PEAK_KEYS.map(([key]) => key),
      ...Object.keys(flightRecord).filter(
        (key) => !FLIGHT_KEYS.includes(key as never) && !PEAK_KEYS.some(([peakKey]) => peakKey === key)
      )
    ];
    const flightAttrs: Attr[] = orderedKeys
      .filter((key) => flightRecord[key] !== undefined && flightRecord[key] !== '')
      .map((key) => ({ key, value: flightRecord[key] }));

    // Verify: a migration only FAILS if it discards a meaningful per-altimeter
    // value (real data loss). Unifying a blank/"unknown" placeholder up to the
    // flight value is the intended behavior and only logged as a warning.
    for (const altimeter of altimeters) {
      const exp = expected.get(altimeter.name)!;
      for (const key of FLIGHT_KEYS) {
        const merged = flightRecord[key] || altimeter.record[key] || '';
        if (merged === exp[key]) continue;
        if (isMeaningful(exp[key])) {
          verifyFailures.push(`${flightEntry.name}/${altimeter.name}: "${key}" loses "${exp[key]}" -> "${merged}"`);
        } else {
          warnings.push(`${flightEntry.name}/${altimeter.name}: "${key}" unified "${exp[key] || '(blank)'}" -> "${merged}"`);
        }
      }
    }

    if (!checkOnly) {
      await writeAttrs(path.join(flightDir, ATTRIBUTES_FILE_NAME), flightAttrs);
      migratedFlights += 1;
      for (const altimeter of altimeters) {
        const remaining = altimeter.attrs.filter((a) => !FLIGHT_KEYS.includes(a.key as never));
        if (remaining.length !== altimeter.attrs.length) {
          await writeAttrs(altimeter.file, remaining);
          rewrittenAltimeters += 1;
        }
      }
    }
  }

  console.log(
    checkOnly
      ? `Check complete. ${warnings.length} warning(s), ${verifyFailures.length} verify failure(s).`
      : `Migrated ${migratedFlights} flight(s); rewrote ${rewrittenAltimeters} altimeter file(s).`
  );
  for (const warning of warnings) console.log(`  warn: ${warning}`);
  for (const failure of verifyFailures) console.log(`  FAIL: ${failure}`);
  if (verifyFailures.length > 0) process.exitCode = 1;
}

void main();
