/* Headless check: saveFlightAttributes merges manual keys while preserving the
 * autogenerated flight-level peaks; readFlightAttributes round-trips. */
import { cp, mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { readFlightAttributes, saveFlightAttributes } from '../src/main/importService';

const FLIGHT = '2022-04-23 Super Guppy';

async function main() {
  const tmp = await mkdtemp(path.join(tmpdir(), 'rfd-verify-'));
  try {
    await cp(path.join('flight-data', FLIGHT), path.join(tmp, FLIGHT), { recursive: true });

    await saveFlightAttributes(tmp, FLIGHT, [
      { key: 'motor', value: 'TESTMOTOR' },
      { key: 'flight_location', value: 'TESTLOC' }
    ]);

    const onDisk = await readFile(path.join(tmp, FLIGHT, 'attributes.csv'), 'utf8');
    const record = Object.fromEntries(
      onDisk.split(/\r?\n/).filter(Boolean).slice(1).map((line) => line.split(','))
    );
    const roundTrip = await readFlightAttributes(tmp, FLIGHT);
    const motor = roundTrip.find((a) => a.key === 'motor')?.value;

    const checks = [
      ['motor updated on disk', record.motor === 'TESTMOTOR'],
      ['location updated on disk', record.flight_location === 'TESTLOC'],
      ['peak_altitude_m preserved', record.peak_altitude_m === '354.42'],
      ['peak_velocity_ms preserved', record.peak_velocity_ms === '72.14'],
      ['flight_date preserved', record.flight_date === '2022-04-23'],
      ['readFlightAttributes round-trip', motor === 'TESTMOTOR']
    ] as const;

    let ok = true;
    for (const [label, pass] of checks) {
      console.log(`${pass ? 'PASS' : 'FAIL'}: ${label}`);
      if (!pass) ok = false;
    }
    process.exitCode = ok ? 0 : 1;
  } finally {
    await rm(tmp, { recursive: true, force: true });
  }
}

void main();
